canonical/tdx

README.md, guest-tools/run_td.sh, setup-host.sh
- Add grub-update command in setup-host.sh to make the kernel argument effective
- Improve README
- Remove useless QEMU argument in run_td.sh script
=> Improvements of instructions

setup-tdx-guest.sh
=> Remove useless modprobe conf for loading tdx guest driver module

README.md, guest-tools/run_td_virsh.sh, guest-tools/td_guest.xml, guest-tools/td_guest.xml.template
Some enhancements to the libvirt instructions + cleanup:
- put virsh instructions in a script to simplify the README
- put log in section after the libvirt section 
- cleanup whitespace
=> Libvirt usage enhancement

guest-tools/image/create-td-image.sh
With different host configuration and network env, script may fail at any unexpected point, add more checkpoint for it.
=> Add checkpoint for create-td-image.sh

guest-tools/run_td.sh
Enhance script output on error
Fix #28
=> Set default path of TD image to right location

guest-tools/image/create-td-image.sh
=> Fix permissions error for create-td-image.sh while accessing guest image

setup-tdx-host.sh
- do not use meta package kobuk-tdx-host anymore there is no value added by using meta package because we already have this script and the use of meta-package can induce some robustness problem when using already has qemu/libvirt installed in the system when doing the setup
- force kernel -intel selection for next boot
Fix #31
=> setup-tdx-host.sh : improve host setup robustness

attestation/setup-attestation-guest.sh, attestation/setup-attestation-host.sh
Release the attestation components in release TDX PPA : https://launchpad.net/~kobuk-team/+archive/ubuntu/tdx-release
=> Dev release attestation

guest-tools/td_virsh_tool.sh
To be able to list current VMs, this is important to see the forwarding ports for ssh connection
=> Add list command to td_virsh_tool

setup-tdx-host.sh
set -e will make the script stop at the check of grub kernal commandline
=> Fix use of set -e option

README.md, setup-tdx-host.sh
For now, we ask users in the README to do it
But we can try to do it for them
=> add user to kvm group

README.md
Addresses https://github.com/canonical/tdx/issues/67 and https://github.com/canonical/tdx/issues/68
After considering how best to update the script to avoid confusion around the issues above, and through discussions with @hector-cao , I eventually decided it best to limit the changes to docs improvements. 
The script is already quite complex as it's managing overlay images, host ssh ports, and CIDs that are unique to each guest (to enable multi guest support) with its own `td_guest` naming prefix (almost like a namespace). We want to avoid making it more complex and to avoid re-implementing all of `virsh`'s functionality. Interacting with the guests through `virsh` directly is more future-proof, while hopefully the script is convenient for creating multiple guests in a reproducible way. …
=> Improve td_virsh_tool docs

README.md
=> dev guest customization

README.md
=> Update Ubuntu 24.04 server download URL in readme

guest-tools/image/create-td-image.sh
Please check issue #145 for details.
Fixes #145
=> Add more information in case of tdx-config-cloud-init failure

README.md
=> Improve the instruction to check guest tdx driver in the guest

guest-tools/run_td.sh
Error was hidden in logfile, hence user doesn't have any clues about the cause of failure, similar to issue #145.
In this case port `SSH_PORT 10022` was already in use and [qemu-system-x86_64](https://github.com/canonical/tdx/blob/noble-24.04/guest-tools/run_td.sh#L33) logs error in logfile but doesn't provide that info to user.
This PR provide logfile info to user in case of failure.
=> Give logfile info in case of failures

LICENSE, LICENSE.apache2, attestation/check-production.sh, attestation/setup-attestation-guest.sh, attestation/setup-attestation-host.sh, guest-tools/image/create-td-image.sh, guest-tools/image/setup.sh, guest-tools/run_td.sh, guest-tools/tdvirsh, setup-tdx-common, setup-tdx-config, setup-tdx-guest.sh, setup-tdx-host.sh, tests/run.sh, tests/run_checkbox, tests/run_pytest
Move to GPLv3 to be compliant with Canonical licensing policy
=> Update LICENSE file

README.md, guest-tools/trust_domain-sb.xml.template
=> Enable secure boot for TD VM

guest-tools/image/create-td-image.sh
if we run the create-td-image.sh in a system that lacks KVM support, the image creation fails (`virt-install` tool fails)
virt-install has support to use qemu instead of kvm; so use it as a fallback since qemu offers a lower performance than kvm (on a system, we spend 2m to create an image with KVM and 7m to create an image with QEMU)
=> create-td-image : use qemu virt type for virt-install if kvm is missing

attestation/setup-attestation-guest.sh, attestation/setup-attestation-host.sh, setup-tdx-common, setup-tdx-config
Move the attestation components to a separate PPA (tdx-attestation-release)
PEK-832
=> Separate attestation packages into a new PPA

guest-tools/image/create-td-image.sh
=> Fix virt-customize resize partition failure

README.md
Add kernel building instructions.
=> README.md: add kernel building section

tests/common.py, tests/lib/Qemu.py, tests/setup_guest.sh, tests/tests/test_boot_basic.py, tests/tests/test_guest_eventlog.py, tests/tests/test_guest_measurement.py, tests/tests/test_guest_reboot.py, tests/tests/test_guest_report.py, tests/tests/test_quote_configfs_tsm.py
Create common funtion to deploy the tests code to the guest and run the guest setup script to properly setup the guest before the test
=> Improve the guest setup setup

README.md, attestation/check-production.sh
Remove SRF from check_production.sh since it's not launched yet.
=> Add GNR to list of supported CPUs in Readme

tests/checkbox/checkbox-provider-tdx/units/tests/jobs.pxu, tests/tests/test_guest_memory.py
JIRA: https://warthogs.atlassian.net/browse/PEK-1285
Adding tests to verify confidentiality with TDX and verify lack of confidentiality without TDX.
=> Adding memory confidentiality tests

tests/tox.ini
allow to display the list of tests
=> tests : add tox command to collect tests

.github/workflows/create-snap-action.yml, tests/README.md, tests/checkbox/bin/checkbox-cli-wrapper, tests/checkbox/bin/checkbox-cli-wrapper-image, tests/checkbox/bin/checkbox-cli-wrapper-local, tests/snap/hooks/configure, tests/snap/snapcraft.yaml
- set the tdx checkbox snap version to 1.0.0
- publish the snap in edge channel at every commit in branch noble-24.04
PEK-854
=> gh action to publish the provider snap

tests/snap/snapcraft.yaml, tests/tox/setup-env-tox.sh
The test tests/test_guest_tsc_config.py needs cpuid package
=> needs cpuid package on the host

README.md
to obtain an API key for attestation.
=> Add step to get free trial of Intel Tiber Trust Service

.github/workflows/create-snap-action.yml, tests/bin/setup-env-and-run, tests/checkbox/bin/checkbox-cli-wrapper, tests/checkbox/bin/checkbox-cli-wrapper-image, tests/checkbox/bin/configure, tests/checkbox/bin/install-full-deps, tests/checkbox/bin/wrapper_local, tests/snap/hooks/configure, tests/snap/snapcraft.yaml
- Move to core24 / Checkbox24
- Cleanup
- 
PEK-1351
=> Noble 24.04 move snap provider checkbox24

attestation/scripts/jwt-decode.sh
Example of usage:
```
echo eyJhbGciOiJQUzM4NCIsImprdSI6Imh0dHBzOi8vcG9ydGFsLnRydXN0YXV0aG9yaXR5LmludGVsLmNvbS9jZXJ0cyIsImtpZCI6ImM2OGU1YTdiM2FlYzUxYTNmZjM4NGZlMzA3OTlkNDY1ZDU1YjE2ZDU3ZWY4OGQwNWY2MDY3NTU5ZDkxNTZjZDNkNTMwMmY4OWZlNjY1ZDFmYjlhNmJlNDYwMmJlMTFkOCIsInR5cCI6IkpXVCJ9.eyJhdHRlc3Rlcl90Y2JfZGF0ZSI6IjIwMjQtMDMtMTNUMDA6MDA6MDBaIiwiYXR0ZXN0ZXJfdGNiX3N0YXR1cyI6IlVwVG9EYXRlIiwiYXR0ZXN0ZXJfdHlwZSI6IlREWCIsImRiZ3N0YXQiOiJkaXNhYmxlZCIsImVhdF9wcm9maWxlIjoiaHR0cHM6Ly9wb3J0YWwudHJ1c3RhdXRob3JpdHkuaW50ZWwuY29tL2VhdF9wcm9maWxlLmh0bWwiLCJpbnR1c2UiOiJnZW5lcmljIiwicG9saWN5X2RlZmluZWRfY2xhaW1zIjpudWxsLCJwb2xpY3lfaWRzX21hdGNoZWQiOm51bGwsInBvbGljeV9pZHNfdW5tYXRjaGVkIjpudWxsLCJ0ZHhfY29sbGF0ZXJhbCI6eyJxZWlkY2VydGhhc2giOiJiMmNhNzFiOGU4NDlkNWU3OTk0NTFiNGJmZTQzMTU5YTBlZTU0ODAzMmNlY2IyYzBlNDc5YmY2ZWUzZjM5ZmQx …
```
=> Add script to dump the attestation token

README.md
thanks @BFuhry for having pointed this issue out
=> README.md : fix branch name

README.md
Migrated from gitea to forgejo.
=> README.md: update kteam-tools repo url

setup-tdx-guest.sh, setup-tdx-host.sh
As of now, the setup scripts tells grub (grubenv)
to boot on the latest -intel kernel revision we have at the time of running the script.
If apt upgrade is invoked later and a new revision of -intel is available, this new kernel will not be set as kernel for next boot because apt upgrade is not aware about the setting we did with grubenv. As consequence, the old kernel revision is still the one the host will boot on.
To allow user to upgrade the kernel, this commit adds the `upgrade` option to the setup scripts.
=> Fix upgrade for the kernel

setup-tdx-guest.sh
=> Fix nvidia drivers installation failure

guest-tools/run_td
the scripts does not parse correctly the list
of gpus.
=> run_td : fix multiple gpus argument
