canonical/tdx

- README.md
https is simpler and has more chance to success for usages with proxy
> README : use https instead of ssh for git clone

- README.md
- guest-tools/run_td.sh
To be able to run the run_td script with normal user the user must be assigned to group kvm. Update README and add a check in the run_td script
> Fix run_td script permission denied issue

- setup-tdx-host.sh
The released intel-opt kernel has an issue with video mode setting that made display unavailable for login prompt on the TTY, as a work around, disable the video mode setting in the kernel
> Work around for login prompt missing issue

- guest-tools/td_guest.xml.template
This change is to launch a TD in TDX non-Debug mode by default.  If a user wants to debug, they should have to explicitly set bit 0 to opt in, in my opinion.
Reference for this in the Intel TDX Module 1.0 Specification, table 22.2 and section 16.3 (https://www.intel.com/content/www/us/en/developer/tools/trust-domain-extensions/documentation.html),
and the TDX source (https://github.com/intel/qemu-tdx/blob/7a97b8940d938d0d5740c0513c9acf0053c6cb85/target/i386/kvm/tdx.c#L51)
> Default TD launch policy to non-debug.

- guest-tools/image/cloud-init-data/user-data
- guest-tools/image/cloud-init-data/user-data.template
The TDX setup process is nice and won't break the apt system, so "apt install --fix-broken" is redundant.
Also remove IMA parameters from guest kernel cmdline to avoid confusion. Enabling TDX doesn't require kernel IMA at all.
> Remove useless apt cmd and IMA config in TDX image creation

- README.md
This makes the source download instructions in our README more generic, now that we are generating [tagged releases in this repo](https://github.com/canonical/tdx/releases). It is the user's responsibility to determine the appropriate method depending on his/her need. 
For example, someone wanting to test a new kernel or qemu feature may want code from the latest stable release, while someone wanting to modify this repo's scripts may want to clone the repo and work from the tip of the appropriate git branch.
> Update source download instructions

- README.md
- attestation/setup-attestation-host.sh
- Add reboot instruction in README  
after the setup script run for attestation, we need to reboot
to have the right owner & group for /dev/sgx_provision (from udev rule)
- Remove README section on use_secure_cert  
with the version 1.18-0ubuntu2 of libsgx-dcap-default-qpl
the use_secure_cert is set to false by default
- setup-attestation-host.sh : do not set user and group for /dev/sgx_provision  
the udev rules will take care of it
> Improve attestation setup script

- setup-tdx-host.sh
In https://github.com/canonical/tdx/pull/47 , we introduced a regression by not installing modules-extra anymore. This module is still needed for some kernel modules that live in modules-extra (igc, ...)
Fixes #54
> Fix network module missing

- README.md
- guest-tools/image/create-td-image.sh
- guest-tools/image/setup.sh
- setup-tdx-guest.sh
Use has to set the environment variable TDX_GUEST_SETUP_INTEL_KERNEL at setup-tdx-guest.sh script invocation
> Add intel kernel as option that can be selected at guest image creation 

- setup-tdx-guest.sh
The tdx-guest module is still in modules-extra, we have to install it for the guest if it uses the generic kernel
> setup-tdx-guest : install modules extra for generic kernel

- guest-tools/td_virsh_tool.sh
- setup-tdx-guest.sh
- setup-tdx-host.sh
Fix shellchecks warnings in setup-tdx* and in guest-tools/td_virsh_tools.sh as they can hide errors.
> Fix shellcheck warnings

- guest-tools/image/create-td-image.sh
- setup-tdx-common
- setup-tdx-guest.sh
- setup-tdx-host.sh
unattended-upgrade revert back to ubuntu components (qemu, libvirt), we must configure unattended-upgrade to take into consideration our pinning configuration
> Fix tdx components pinning despite unattended upgrade

- README.md
- guest-tools/image/create-td-image.sh
- guest-tools/run_td.sh
- guest-tools/td_guest.xml.template
Reduce the vcpu number of guest to reasonable numbers
TDX does not support multi-sockets for TD so set the socket to 1
Increase timeout for virt-install when creating guest image
README : improve host verification of tdx initialization
> corrections and updates

- setup-tdx-common
- setup-tdx-guest.sh
- setup-tdx-host.sh
so far, a specific kernel version (6.8.0-1001-intel) is installed and the system will stick to it (when setup script is run again or at system upgrade). we would like to get the latest version of the kernel (for example, when 6.8.0-1002-intel will be released) automatically without having to modify the script.
> change kernel installation policy

- guest-tools/run_td.sh
Recommend to use tsc as the clocksource in TD guest and not to use hpet. Without hpet=off, the default clocksource in TD guest is also tsc, but the users can change the closcksouce by themselves. So we disable hpet in qemu para to ensure hpet will not be used in TD guest.
> run_td.sh: add hpet=off

- README.md
- guest-tools/image/create-td-image.sh
- guest-tools/run_td.sh
- guest-tools/td_virsh_tool.sh
Addresses https://github.com/canonical/tdx/issues/72
System: right-glider
```bash
$ # create generic image
$ sudo ./create-td-image.sh
.
.
$ ls *.qcow2
tdx-guest-ubuntu-24.04-generic.qcow2
$ # create intel image
$ sudo TDX_GUEST_SETUP_INTEL_KERNEL=1 ./create-td-image.sh  
.
.
$ ls *.qcow2
tdx-guest-ubuntu-24.04-generic.qcow2  tdx-guest-ubuntu-24.04-intel.qcow2
```
```bash
$ # run TD with default generic kernel
$ ./run_td.sh   
TD VM, PID: 3867045, SSH : ssh -p 10022 root@localhost
$ ssh -p 10022 root@localhost "lsb_release -a; uname -r; dmesg | grep -i tdx"
.
.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
6.8.0-31-generic
[    0.000000] tdx: Guest detected
[    0.558487] process: using TDX aware idle routine
[    0.641704] Memory Encryption Features …
```
> Use kernel flavor in QEMU image name

- README.md
- attestation/setup-attestation-guest.sh
- attestation/setup-attestation-host.sh
- guest-tools/image/create-td-image.sh
- guest-tools/image/setup.sh
- setup-tdx-config
- setup-tdx-guest.sh
- setup-tdx-host.sh
put all variables in a config file : setup-tdx-config
clean up setup scripts in the guest at the end
allow downgrade for attestation packages
> improvement setup configuration management

- README.md
- guest-tools/run_td.sh
- guest-tools/tdvirsh
- setup-tdx-config
- setup-tdx-host.sh
- tests/checkbox-provider-tdx/bin/perf_benchmark.py
- tests/checkbox-provider-tdx/bin/perf_boot_time.py
- Consistently use Intel TDX.
- Use new names, e.g., Intel TDX Loader and Intel Tiber Trust Services.
- Remove all usages of TDVM, TD VM, or TD guest, because a TD is by definition a VM protected by Intel TDX making these terms superfluous.
- Streamline structure by using indentations, rearranging some text, and introducing sub section numbers.
- Other minor text changes.
> Adjust documentation of Ubuntu 24.04 version

- README.md
Recently, we switched to use a configuration file to centralize the configuration for the setup process. We do not ask users to set directly env variables anymore.
> Fix readme for switching to -intel kernel

- setup-tdx-common
- setup-tdx-config
- setup-tdx-guest.sh
- setup-tdx-host.sh
The PPA used for tdx packages is tdx-release.
For development purpose, we might want to switch back to the dev PPA (tdx). Add a variable in the config file for that.
> Add configuration variable to allow to switch TDX PPA

- README.md
This PR is in response to issue #78
> Clarify Intel PCS subscription key retrieval in README

- tests/checkbox/bin/checkbox-cli-wrapper
- tests/checkbox/checkbox-provider-tdx/units/basic/jobs.pxu
- tests/pytest/setup-env-and-run
- tests/run.sh
- tests/run_checkbox
This is a first step for internal JIRA PEK-710.  This is to get checkbox working with the existing set of tests.  Next steps:
* Add the rest of the pytests
* Cleanup documentation and directories to align with pytests and new checkbox implementations
* Verify consistency of testing
> Fixing up checkbox tests to run same tests as pytest

- tests/snap/snapcraft.yaml
Simple fix for the snap builds.  More work in future pulse to deal with where the guest qcow2 image gets referenced.
> PEK-710 - fix snap build

- tests/checkbox/checkbox-provider-tdx/units/basic/jobs.pxu
- tests/pytest/setup-env-and-run
- tests/pytest/test_guest_measurement.py
- tests/run_checkbox
All tests available were added.  Put reports generated into /var/tmp/tdxtest/reports (as checkbox calls pytest).
Removed td-perf-benchmark as it doesn't seem to complete after several hours.  Will resolve later.
This is a continuation of other PEK-710 pull request.
> Adding all pytests to checkbox list for PEK-710

- README.md
This PR add info to main README to detect and fix [Platform registration](https://github.com/canonical/tdx/blob/a8261b15784a5bd9962bbc5af63d27444b8bbb3c/README.md?plain=1#L376) failures.
Fixes #131
> Detect and fix platform registration failures

- attestation/check-production.sh
- attestation/setup-attestation-guest.sh
- attestation/setup-attestation-host.sh
- guest-tools/image/create-td-image.sh
- guest-tools/image/setup.sh
- guest-tools/run_td.sh
- guest-tools/tdvirsh
- setup-tdx-guest.sh
- setup-tdx-host.sh
- tests/run.sh
- tests/run_pytest
Shebangx needs to be on the first line of the file to be effective. Move back all license notice after the shebang.
> licence: fix shebangs and licence

- .github/workflows/create-snap-action.yml
Adding github action to create snap build on repo push using github hosted runner. Notes:
-  When using snapcraft, the created container, during snapcraft build, doesn't appear to get an IP address and, as a result, doesn't work properly without using "--destructive" option of snapcraft
- When using "--destructive" mode of snapcraft, we can't use 22.04 (jammy) since the snap is meant to be built with 24.04 (noble).  Therefore, we have to use "24.04" (noble) as the "runs-on" option for github action
> Pek 743 create github action for snap build on repo push

- guest-tools/image/create-td-image.sh
Improve create-td-image script log to invite users to wait for long running operations
Fix #93
Fix #112
> Dev improve log

- guest-tools/regular_vm.xml.template
- guest-tools/trust_domain-sb.xml.template
- guest-tools/trust_domain.xml.template
The domain definition already enforces usage of host-passthrough CPU mode, so adding -cpu host is redundant.
> Remove redundant -cpu option of qemu

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support.md
- system-report.sh
This adds issues template and a system reporting script to help us to better support users of this repo and triage issues.
There may be other system details that would be helpful here. For example, is it possible to get the tdx module version from the CLI (I briefly searched around but did not come across anything)? Or are there other packages that should be included?
For reference, I'm pasting the results of running the system report script from a production system below. Some notes about the output:
* I personally think it's most convenient (both for users and maintainers) to have the report directly in the body of the issue rather than uploading a file. 
* I also considered a bulleted list rather than entire sections but I found the section-based approach easier to read/parse.
``` …
```
> Add GitHub issues template and related system report script

- system-report.sh
- Install msr-tools and load msr driver if not present this is required to read MSR values
- MSR value : rename HW_ENCRYPT_ENABLE to MK_TME_ENABLE
- Add check production to MSR section
- Nicely handle the case where mpa_registration.log is not available
Fixes #192
> system-report.sh : various fixes

- guest-tools/run_td.sh
- guest-tools/trust_domain-sb.xml.template
- guest-tools/trust_domain.xml.template
Fixes  #178 
PEK-905
A fix on libvirt has been done to use the right qemu argument to specify the QGS communication channel
this fix will also rename the libvirt conf field name from `Quote-Generation-Service` to `quoteGenerationService`
This commit will update the libvirt configuration to use the new libvirt configuration option
It also updates  the `run_td.sh` script to add support for the qemu QGS option
> Dev fix quote generation configfs tsm

- attestation/setup-attestation-host.sh
this package is necessary of user does not provide its own provider implementation
> setup-attestation-host: install the libsgx-dcap-default-qpl package

- guest-tools/image/setup.sh
livecd-rootfs disables the password auth method for sshd by adding sshd config snippet 60-cloudimg-settings.conf the passord auth method is still possible with the keyboard-interactive method but when a client specifies password as the only authorized method by issuing: ssh -o PreferredAuthentications=password ... the auth fails.
Fixes #209
> Allow password authentication method for ssh

- tests/tox.ini
This variable is to specify the tests to not clean up the guest VMs This is useful for debugging purposes
> tests: tell tox to capture the TDXTEST_DEBUG variable

- tests/lib/Qemu.py
- tests/tests/setup-env-tox.sh
- tests/tests/test_guest_cpu_off.py
- tests/tests/test_guest_fail.py
- tests/tests/test_guest_tsc_config.py
- tests/tests/test_host_tdx_software.py
- tests/tox.ini
Adding tests to tdx set.  Still need to add to checkbox tests in a separate PR with the rest of the tests specified in PEK850 in next pulse.
Fixes PEK-850
> PEK 850: Adding part of the higher priority tests

- guest-tools/regular_vm.xml.template
- guest-tools/trust_domain-sb.xml.template
- guest-tools/trust_domain.xml.template
It is easier to work with Gb unit, this change is to ease the users when they want to quickly configure the VM memory to an other value for testing
> Use GiB as unit for memory conf in libvirt configuration

- tests/tests/test_guest_tsc_config.py
we actually want to check guest dmesg log instead of host's log
> tests : fix test_guest_tsc_config test

- tests/lib/Qemu.py
- tests/tests/conftest.py
- In case of test failure, we would like that the workdir of qemu is not cleaned up so that we can do some debugging.
- Improve the management of environment variable TDXTEST_DEBUG that forbids the clean up of these workdirs at any case
> Improve the management of workdir cleanup for debugging purposes

- tests/tox.ini
- tests/tox/setup-env-tox.sh
- simplify and improve tox setup script
remove useless python package installation because they are already installed in the tox venv
- move tox setup script in tox folder
this prevents the deployment of this script into the checkbox provider that does not use this script
> improve tox setup script and config

- README.md
Make the link generic instead of a specific version of the ISO.
This prevents it from breaking each time a new dot release is published.
> Make link to Noble ISO generic 

- tests/lib/Qemu.py
- tests/tests/conftest.py
- tests/tests/test_boot_basic.py
- tests/tests/test_boot_coexist.py
- tests/tests/test_boot_multiple.py
- tests/tests/test_boot_td_creation.py
- tests/tests/test_guest_cpu_off.py
- tests/tests/test_guest_eventlog.py
- tests/tests/test_guest_fail.py
- tests/tests/test_guest_measurement.py
- tests/tests/test_guest_report.py
- tests/tests/test_guest_tsc_config.py
- tests/tests/test_nmi_debug_off.py
- tests/tests/test_perf_boot_time.py
- tests/tests/test_quote_configfs_tsm.py
- tests/tests/test_stress_boot.py
- tests/tests/test_stress_resources.py
- tests/tests/test_vsock_vm.py
each test usually runs a qemu process, for several reasons (test badly written, test failure, ...), the qemu process can still be running after the test and this might block some tests on reloading the kvm kernel module (because it is used) this commit aims to provide several tools:
- qemu machine as a context manager when we write a test and needs to create a qemu machine, we can use the context manager to make sure that the machine is released at the end of the test (even on failure)
- test fixture that cleans up all running qemu instances, each test can request this fixture in the test argument so that before the test start, all running qemu are stopped.
- Fixes #225
> fix kvm_intel module reload issue

- tests/checkbox/checkbox-provider-tdx/units/tests/jobs.pxu
- tests/tests/test_guest_ita.py
- tests/tests/test_guest_measurement.py
https://warthogs.atlassian.net/browse/PEK-614
Adding trustauthority-cli quote test.
> Pek614 adding attestation type tests

- tests/lib/util.py
- tests/tests/conftest.py
- tests/tests/test_guest_cpu_off.py
- tests/tests/test_guest_fail.py
- if we pin the process to a offline cpu core, the test will fail we need to bring the core online fist
- add a cpu manager as context manager to easily restore the core state at the end of the test
- move some utility code to util.py
- make cpu random select more robust since on some systems core0 might not support the on/off feature (IRQ is wired on it)
> test_guest_cpu_off: fixes failure

- tests/lib/Qemu.py
- tests/tests/test_boot_basic.py
right now, we are testing the host kernel
actually, we want to do this test for the guest VM kernel
I propose to fix that by redesigning the test in 2 steps:
- append the wanted kernel commandline in the guest VM
- restart the guest VM
> test_guest_early_printk : test with the kernel in the guest VM

- system-report.sh
GH issue accepts comments with length less than 65k characters with dmesg output, if the machine is up and running for a quite long period it can generate very long  output
To mitigate this issue, we limits the dmesg output to the first 10 lines and 20 last lines only. The first 10 lines allow us to see the tdx module load and the 20 last lines might show us the log that happens during the issue
> system-report : fix too long output for GH issue

- tests/tests/test_host_kdump.sh
- tests/tests/test_host_kexec.sh
https://warthogs.atlassian.net/browse/PEK-852
Adding kexec/kdump tests for the host.  This requires the host to be rebooted effectively multiple times.  So, this was written as a shell script that can be used, eventually, in testflinger, or in a runner.
> Kexec/Kdump Tests

- README.md
- guest-tools/regular_vm.xml.template
- guest-tools/tdvirsh
- guest-tools/trust_domain-sb.xml.template
- guest-tools/trust_domain.xml.template
This work has been motivated by the demo we were trying to do for Confidential RAG where we will need multiple TD VMs to communicate between them.
With this change, the guest will be accessible via it own IP:
```shell
ssh root@<IP>
```
instead of 
```shell
ssh -p <forward-port> root@localhost
```
And `tdvirsh list` will also print the guest IP:
```
$ ./tdvirsh list
Id   Name                                                        State 
--------------------------------------------------------------------------- 
2    tdvirsh-trust_domain-508f629e-4e86-4969-8517-da1ba35258ed   running (ip:192.168.122.212, hostfwd:44321, cid:3)
```
> add network to guest to make it accessible via IP  

- tests/checkbox/checkbox-provider-tdx/units/tests/jobs.pxu
- tests/lib/Qemu.py
- tests/tests/test_guest_ita.py
- tests/tests/test_guest_tdxattest.py
This PR adds tests for the libtdx_attest library in the TD VM guest
> add tests for libtdx_attest

- README.md
Use `pull-ppa-source` instead of `apt source` to make sure we get the source from the Kobuk PPA instead of the Ubuntu archive
> Improve package build from source instructions

- tests/lib/tdx-tools/src/tdxtools/host.py
- tests/tests/test_host_tdx_software.py
On host system that supports TDX, the CPU info (`lscpu` or `/proc/cpuinfo`) should have the flag `tdx_host_platform`
> tests: add test to check tdx flag in CPU info

- tests/tests/test_quote_configfs_tsm.py
currently in the test tests/test_quote_configfs_tsm.py::test_qgs_socket we modify permanently the qemu -machine and -object arguments. this can make following tests fail
we do not want to modify these arguments permanently but only for the current test
> fix failing tests cause of permanent modification of qemu machine arguments

- tests/checkbox/checkbox-provider-tdx/units/tests/jobs.pxu
- tests/snap/snapcraft.yaml
vsock test uses a customized iperf tool with vsock support
this tool is installed on the host
however, checkbox24 comes with iperf tool and it will be used by the test,
without vsock support, the test fails
we device to bundle the customized iperf tool to the checkbox provider
and set PATH variable to use the iperf in the provider
one other solution would be to set the PATH to use the iperf installed on the system
but we think that bundle iperf3 into the provider is a better approach
> fix failing test vsock in checkbox provider

- tests/tests/test_stress_quote.py
manually, on some systems, when we loop on requesting the quote generation, the host seems to be in heavy load and becomes unresponsive, add the stress test case for that.
> tests : add stress test for quote generation

- tests/lib/Qemu.py
- tests/tests/test_guest_ita.py
- tests/tests/test_guest_tdxattest.py
- tests/tests/test_quote_configfs_tsm.py
- tests/tests/test_stress_quote.py
this test will contribute to verify the issue #252 
the test that checks the issue is `tests/test_guest_tdxattest.py::test_guest_tdxattest_vsock_wrong_qgs_addr`
it currently fails and should succeed once the issue is resolved
```
QemuMachine created.
qemu-system-x86_64 -cpu host -smp 16,sockets=1 -accel kvm -nographic -nodefaults -no-user-config -m 2G -bios /usr/share/ovmf/OVMF.fd -object {'qom-type': 'tdx-guest', 'id': 'tdx', 'quote-generation-socket': {'type': 'vsock', 'cid': '3', 'port': '4050'}} -machine q35,kernel_irqchip=split,confidential-guest-support=tdx -drive file=/tmp/tdxtest-default-xc64ol1d/image.qcow2,if=none,id=virtio-disk0 -device virtio-blk-pci,drive=virtio-disk0 -pidfile /tmp/tdxtest-default-xc64ol1d/qemu.pid -monitor …
```
> add test to check quote generation via vsock

- guest-tools/run_td.sh
Currently, `run_td.sh `shows `ssh `command only for root user.
It does not show TD login information for the default user.
It also does not show TD login information for customized TD guest user(specified during TD image creation)
1. Please follow the instructions given [here](https://github.com/canonical/tdx/tree/noble-24.04?tab=readme-ov-file#51-create-a-new-td-image) to create a TD image.
2. Follow the instructions given [here](https://github.com/canonical/tdx/tree/noble-24.04?tab=readme-ov-file#61-boot-td-with-qemu) to boot the TD with qemu.
3. TD login information with `ssh`commands will be displayed
> Display login information of non-root user in addition to root user

- guest-tools/image/create-td-image.sh
for now, if the host does not have /dev/kvm available the image creation always fails even if the image can be created successfully in QEMU mode
Fixes #261
> fix failure in no kvm mode for creating image

- guest-tools/image/create-td-image.sh
as of now, the user can run the script as non root user however, this leads to permission errors that can be complex to fix i don't think it is worth the game to allow normal user to run this script
so, from now on, we require root/sudo for running this script to avoid ending up in weird error situations
Fixes #258
> create-td-image.sh : enforce root requirement

- tests/lib/setup_guest.sh
- tests/snap/snapcraft.yaml
- tests/tox/setup-env-tox.sh
until now, the packages (vsock-iperf) are uploaded in the testing PPA this testing PPA is a temporary PPA used for various debugging purposes and can be removed at any time, we created a new PPA dedicated to host test packages for TDX (tdx-testing)
this patch make the TDX tests use this new PPA
> tests : move packages used by TDX test to tdx-testing

- tests/lib/Qemu.py
This PR comes with 2 commits:
- output the qemu command to a script
this will allow users to run manually the guest after the test
this capability is useful for debugging purposes
for example, the user can run the guest manually by doing:
```bash
$ sudo /tmp/tdxtest-default-hk8u6mf3/run.sh
```
`hk8u6mf3` is random and may vary for each test
- right now, we use `proc.terminate()` to send SIGTERM to qemu process
this tends to corrupt the rootfs
this will prevent us from running the guest again with this rootfs
try to stop the VM (shutdown) properly first and terminate() it
later if necessary
> Noble 24.04 minor improvements

- tests/lib/Qemu.py
- tests/tests/test_stress_boot.py
- tests/tests/test_stress_resources.py
- tests/tox.ini
This MR comes as several commits, please check them out separately to have more context of all the changes.
The changes are:
- renaming of some test functions to be aligned with test file name
- increase ssh connection timeout for some stress tests since the guests can take more time to boot
- tox : add command to run all tests except performance ones
- does not make the test fail if we cannot stop the guest properly via monitor interface since for some tests, the guest may 
be shutdown already, etc ...
- for an unknown reason, we can not have multiple connections to the qemu process monitor interface via unix sock file
only one connection is possible, others are blocked.
for this reason, we will allow only one instance of monitor connection for each qemu process
> several improvements for tests in Ubuntu 24.10

- guest-tools/run_td.sh
The echo command in `run_td.sh` has `tdx` (with backticks) in the below line [line no.78]
`The default non-root user is <backtick>tdx<backtick>`
Because of the backticks, when its printed on shell, it takes `tdx` as a command.
Hence, errors out displaying:
_tdx: command not found_
Adding this change to remove the backticks.
> Add correction to echo command in run_td.sh

- guest-tools/regular_vm.xml.template
- guest-tools/trust_domain-sb.xml.template
- guest-tools/trust_domain.xml.template
until now, libvirt generates apparmor permission
for the OVMF file to "rk" whatever is the value of the readonly flag.
on recent libvirt version 10.0, there is a fix
https://github.com/libvirt/libvirt/commit/c019350a76d79405dd3e22d3023b71384f2924f2 that generates the apparmor permission "rwk" if the flag readonly is set to no (or not set - no is the default value).
however, libvirt has an enforcement on the OVMF.fd file that denies the "w" permission. our qemu process
will failed because of this.
this patch will set the readonly explicitly to yes so that only the permissions "rk" are generated and will pass apparmor control
> libvirt : set ovmf readonly flag to true

- tests/tests/test_guest_tsc_config.py
on 24.10, the VMs takes > 75s to boot if -tsc-deadline is added to cpu argument of qemu
for now, extend the ssh connection timeout to make the test pass
> tests : extend ssh connection timeout for test tsc_deadline disable

- guest-tools/image/cloud-init-data/user-data
- guest-tools/image/cloud-init-data/user-data.template
- guest-tools/image/create-td-image.sh
- guest-tools/run_td.sh
- guest-tools/tdvirsh
- setup-tdx-common
- setup-tdx-config
for now, this branch only supports 24.04, with the upcoming 24.10 support, we would like this branch to offer it instead of using a different branch
this helps us to lower the maintenance effort since the majority of the code base is release agnostic. (especially tests, tools, documentation ....)
> add the management of multiple ubuntu releases

- guest-tools/image/create-td-image.sh
- setup-tdx-config
the image generation script will now be able to generate image for multiple ubuntu releases
To generate the image for 24.04:
```
sudo ./create-td-image.sh  -v 24.04
```
The user needs to specify the version, if not, the script will fail, it will not try to guess the version from the ubuntu host since users can run on a ubuntu release we do not offer TDX support for (for example : 22.04)
> image : add multi release image generation capability

- README.md
- guest-tools/image/create-td-image.sh
From now on, create-td-image.sh will need a ubuntu release as input,
At the moment, 24.04 is the only acceptable value but soon 24.10 will be added with the release for 24.10
Fixes #285
> Update the README for create-td-image.sh

- tests/tests/test_guest_ita.py
The version 1.6.1 for 24.10 changed the output format for the generated quote, we have to modify the tests to take into account this API change
> tests : fix intel trust authority quote generation tests

- setup-tdx-common
- setup-tdx-host.sh
enable by default non root user for libvirt
since everytime, I run into permissions issue and realized I missed this step in the README to enable non-root user
It is a waste of time and this commit tries to automate this for the users
> enable normal user for libvirt in setup script

- attestation/check-registration.sh
- tests/pytest.ini
- tests/tests/conftest.py
- tests/tests/test_guest_ita.py
- tests/tests/test_guest_tdxattest.py
- tests/tests/test_stress_quote.py
when the tests run on platform that is not registered to the intel trust service, quote cannot be generated. in that case, the tests must be skipped.
this commit add a script `check-registration.sh` that allows to detect if the platform has been properly registered, if not, all the tests marked as quote_generation will be skipped
> tests : skip attestation tests if platform is not registered

- guest-tools/image/create-td-image.sh
> create-td-image : on 24.04, the script fails if passt is installed

- attestation/check-registration.sh
mpa_manage -get_last_registration_error_code is not the most accurate mean to check the registration status because it outputs stauts 0 when the registration is in progress (not done)
> fix registration status check

- README.md
- guest-tools/direct-boot/README.md
- guest-tools/direct-boot/boot_uki.sh
- guest-tools/image/create-uki.sh
the improvements are results of the user's feedback on the closed MR : https://github.com/canonical/tdx/pull/296
+ grammar check on README
> improvements on the direct boot using UKI

- setup-tdx-host.sh
- tests/tests/boot/test_boot_basic.py
Right now, when we run the TDX setup, we call grub-install to finalize some kernel boot parameters additions, grub-install modifies the EFI boot order (by modifying the NVRAM). This boot order change will place Ubuntu as the first boot entry and breaks by the way MAAS that expects the machine to PXE boot in the first place.
We use `--no-nvram` argument to tell grub-install to not change the boot order
> Make grub-install to not alter the EFI boot order

- guest-tools/image/create-td-uki.sh
Ubuntu make the kernels (vmlinuz) readable ONLY for root user this makes libguestfs fails when it is run as normal user For more details, see the LP bug on that topic:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725 To work-around this issue, we allow normal users to read the kernel files
Fixes #352 
JIRA #PEK-1760
> create-td-uki : fix permission denied issue

- gpu-cc/h100/setup-gpus.sh
We have to reload the udev rules before running udevadm trigger
Fixes #367
> Dev fix dev rules vfio

- guest-tools/run_td
avx10 is only available in qemu in 25.04, it is not in 24.04 per consequence, only remove it if we are not on 24.04
Fixes #366
> run_td : fix run error on 24.04 because of missing avx10 feature in qemu

- setup-tdx-guest.sh
Since Nvidia fixed the issue for installing the version 750,
We can now remove the work-around
Fixes #386
> setup-tdx-guest : fix nvidia drivers install
